### PR TITLE
Remove the first paragraph

### PR DESCRIPTION
**Pull request by karlhorky**
The first paragraph doesn't add anything to the readme. Maybe you want to remove it?

### CODE REVIEW

**Comment by Josehower** [comment]
Hi, @karlhorky  thanks for this.  just a small change

**Review by Josehower — CHANGES_REQUESTED** [review]
Lets leave an empty line at the start please

**Comment by karlhorky** [comment]
@Josehower great idea! I've added this in [`3276e8d` (#1)](https://github.com/Josehower/next-js-example-jan-2022/pull/1/commits/3276e8d2d2529daf648c27246e3cc15055a668c0)

**Review by Josehower — APPROVED** [review]
nice!! thanks

**Pull request merged**
